apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: badada-frontend-image
  newName: 270112669095.dkr.ecr.ap-northeast-2.amazonaws.com/badada-frontend
  newTag: f3f1db6748b12d84d08396a2d8001dbb27a97f73
