apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: badada-frontend-image
  newName: 270112669095.dkr.ecr.ap-northeast-2.amazonaws.com/badada-frontend
  newTag: a5bcd062057e9e7712e1dff063738dad095b9db0
